import './globals.css'
import { IBM_Plex_Mono } from 'next/font/google'

const ibm = IBM_Plex_Mono({weight: ["400"], subsets: ["latin"]})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${ibm.className} bg-zinc-900 w-screen h-screen text-sky-300`}>
        <div className='container mx-auto w-full'> {children}</div></body>
    </html>
  )
}
